/**
 * ENCRYPTO Icon Library
 * To add a custom icon, simply add a new extension key to the LIBRARY object.
 * Format: "extension": { color: "HEX_COLOR", icon: "SVG_PATH_D", label: "CUSTOM_LABEL" }
 */

const ICON_THEMES = {
    GAME: { color: "#bf4aff", label: "GAME" },      // Purple
    ARCHIVE: { color: "#ffaa00", label: "ARCHIVE" }, // Orange
    SYSTEM: { color: "#8a8a8f", label: "SYSTEM" },   // Grey/Blue
    DOC: { color: "#ffffff", label: "DOC" },         // White
    VIDEO: { color: "#ff4a4a", label: "VIDEO" },     // Red
    AUDIO: { color: "#ff4ac0", label: "AUDIO" },     // Pink
    IMAGE: { color: "#4ac0ff", label: "IMAGE" },     // Blue
    APP: { color: "#a0ff4a", label: "APP" },       // Green
    CODE: { color: "#f3c845", label: "CODE" },       // Gold
    DATA: { color: "#4afff0", label: "DATA" },       // Cyan
    FONT: { color: "#a0c0ff", label: "FONT" },       // Light Blue
    CONFIG: { color: "#666666", label: "CONFIG" },   // Grey
    PRINT3D: { color: "#4affd0", label: "3D" }       // Teal
};

const ICON_PATHS = {
    GAME: `<path d="M6 12h4m-2-2v4m5-2h.01m2.99 0h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>`,
    ARCHIVE: `<path d="M10 2v4h4V2m-4 4v4h4V6m-4 4v4h4v-4m-4 4v4h4v-4M18 6h-4v14h4a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2zM6 6h4v14H6a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2z"/>`,
    SYSTEM: `<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><circle cx="12" cy="11" r="3"/><path d="m12 14v3"/>`,
    DOC: `<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/>`,
    VIDEO: `<path d="M23 7l-7 5 5 5V7z"/><rect x="1" y="5" width="15" height="14" rx="2"/>`,
    AUDIO: `<path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/>`,
    IMAGE: `<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="M21 15l-5-5L5 21"/>`,
    APP: `<rect x="4" y="4" width="16" height="16" rx="2"/><path d="m9 9 3 3-3 3"/><path d="M15 15h-3"/>`,
    CODE: `<polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/>`,
    DATA: `<path d="M21 12V7H5a2 2 0 010-4h14V2M3 5v14a2 2 0 002 2h16v-5M3 10h18M3 15h18"/>`,
    FONT: `<polyline points="4 7 4 4 20 4 20 7"/><line x1="9" y1="20" x2="15" y2="20"/><line x1="12" y1="4" x2="12" y2="20"/>`,
    CONFIG: `<path d="M12.22 2h-.44a2 2 0 0 0-2 2a2 2 0 0 1-2 2a2 2 0 0 0-2 2a2 2 0 0 1-2 2a2 2 0 0 0-2 2a2 2 0 0 1-2 2a2 2 0 0 0 0 4a2 2 0 0 1 2 2a2 2 0 0 0 2 2a2 2 0 0 1 2 2a2 2 0 0 0 2 2a2 2 0 0 1 2 2a2 2 0 0 0 2 0a2 2 0 0 1 2-2a2 2 0 0 0 2-2a2 2 0 0 1 2-2a2 2 0 0 0 2-2a2 2 0 0 1 2-2a2 2 0 0 0 0-4a2 2 0 0 1-2-2a2 2 0 0 0-2-2a2 2 0 0 1-2-2a2 2 0 0 0-2-2a2 2 0 0 1-2-2a2 2 0 0 0-2-2z"/><circle cx="12" cy="12" r="3"/>`,
    PRINT3D: `<path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/>`
};

const ICON_LIBRARY = {
    // GAMES / ROMS / EMULATION
    "sb3": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "SCRATCH" },
    "sb2": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "SCRATCH" },
    "rom": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "ROM" },
    "sav": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "SAVE" },
    "xci": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "SWITCH" },
    "nsp": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "SWITCH" },
    "nds": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "DS" },
    "gba": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "GBA" },
    "3ds": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "3DS" },
    "wbfs": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "WII" },
    "rvz": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "DOLPHN" },
    "chd": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "RETRO" },
    "pbp": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "PSP" },
    "vpk": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "VITA" },
    "nes": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "NES" },
    "smc": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "SNES" },
    "n64": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "N64" },
    "m3u": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "PLAYST" },
    "pkg": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "PS3_4" },
    "wud": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "WIIU" },
    "wux": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "WIIU" },
    "ciso": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "PSP" },
    "gcm": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "GAMECB" },
    "msf": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME },
    "gb": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "GB" },
    "gbc": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "GBC" },
    "gg": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "G_GEAR" },
    "smd": { ...ICON_THEMES.GAME, icon: ICON_PATHS.GAME, label: "MEGA" },

    // ARCHIVES / DISK IMAGES
    "rar": { ...ICON_THEMES.ARCHIVE, icon: ICON_PATHS.ARCHIVE },
    "rar5": { ...ICON_THEMES.ARCHIVE, icon: ICON_PATHS.ARCHIVE, label: "RAR5" },
    "zip": { ...ICON_THEMES.ARCHIVE, icon: ICON_PATHS.ARCHIVE },
    "7z": { ...ICON_THEMES.ARCHIVE, icon: ICON_PATHS.ARCHIVE },
    "tar.gz": { ...ICON_THEMES.ARCHIVE, icon: ICON_PATHS.ARCHIVE, label: "TAR.GZ" },
    "tgz": { ...ICON_THEMES.ARCHIVE, icon: ICON_PATHS.ARCHIVE, label: "TGZ" },
    "tar": { ...ICON_THEMES.ARCHIVE, icon: ICON_PATHS.ARCHIVE },
    "gz": { ...ICON_THEMES.ARCHIVE, icon: ICON_PATHS.ARCHIVE },
    "bz2": { ...ICON_THEMES.ARCHIVE, icon: ICON_PATHS.ARCHIVE },
    "xz": { ...ICON_THEMES.ARCHIVE, icon: ICON_PATHS.ARCHIVE },
    "wim": { ...ICON_THEMES.ARCHIVE, icon: ICON_PATHS.ARCHIVE, label: "WIM" },
    "gho": { ...ICON_THEMES.ARCHIVE, icon: ICON_PATHS.ARCHIVE, label: "GHOST" },
    "iso": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.ARCHIVE, label: "DISK" },
    "cab": { ...ICON_THEMES.ARCHIVE, icon: ICON_PATHS.ARCHIVE },
    "bin": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.ARCHIVE, label: "BINARY" },
    "cue": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.ARCHIVE, label: "CUE" },
    "img": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.ARCHIVE, label: "IMAGE" },

    // SYSTEM / VIRTUAL / SECURITY
    "dmg": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.SYSTEM, label: "MAC" },
    "vmdk": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.SYSTEM, label: "VM" },
    "ova": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.SYSTEM, label: "VM" },
    "vhd": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.SYSTEM, label: "VIRTUAL" },
    "sys": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.SYSTEM },
    "dll": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.SYSTEM, label: "LIB" },
    "hex": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.SYSTEM, label: "HEX" },
    "ipsw": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.SYSTEM, label: "IPHONE" },
    "dmp": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.SYSTEM, label: "CRASH" },
    "crt": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.SYSTEM, label: "SSL" },
    "pem": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.SYSTEM, label: "KEY" },
    "cer": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.SYSTEM, label: "CERT" },
    "p12": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.SYSTEM, label: "PKCS12" },
    "pfx": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.SYSTEM, label: "PFX" },
    "gpg": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.SYSTEM, label: "GPG" },
    "key": { ...ICON_THEMES.SYSTEM, icon: ICON_PATHS.SYSTEM, label: "KEY" },

    // DOCUMENTS / EBOOKS
    "txt": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC },
    "docx": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC, label: "WORD" },
    "pdf": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC },
    "xlsx": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC, label: "EXCEL" },
    "pptx": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC, label: "POWERP" },
    "odt": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC },
    "ods": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC },
    "rtf": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC },
    "epub": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC, label: "EBOOK" },
    "mobi": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC, label: "KINDLE" },
    "djvu": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC },
    "md": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC, label: "MARKDN" },
    "tex": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC, label: "LATEX" },
    "bib": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC, label: "BIBTEX" },
    "pages": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC, label: "PAGES" },
    "numbers": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC, label: "NUMB" },
    "key": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC, label: "KEYNT" },
    "ics": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC, label: "CAL" },
    "vcf": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC, label: "V_CARD" },

    // VIDEO / PRODUCTION
    "mp4": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO },
    "mkv": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO },
    "avi": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO },
    "mov": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO },
    "wmv": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO },
    "flv": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO },
    "swf": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO, label: "FLASH" },
    "webm": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO },
    "ts": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO },
    "vob": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO, label: "DVD" },
    "m2ts": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO, label: "BD_RAY" },
    "3gp": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO, label: "MOBILE" },
    "m4v": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO },
    "f4v": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO },
    "ogv": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO },
    "prproj": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO, label: "PREMR" },
    "aep": { ...ICON_THEMES.VIDEO, icon: ICON_PATHS.VIDEO, label: "AFTER" },

    // AUDIO / PRODUCTION
    "mp3": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO },
    "wav": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO },
    "flac": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO },
    "m4a": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO },
    "ogg": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO },
    "wma": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO },
    "aac": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO },
    "mid": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO, label: "MIDI" },
    "alac": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO, label: "ALAC" },
    "ape": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO, label: "MONKEY" },
    "opus": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO, label: "OPUS" },
    "aiff": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO, label: "APPLE" },
    "amr": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO, label: "VOICE" },
    "mpc": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO },
    "als": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO, label: "ABLETN" },
    "flp": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO, label: "FL_ST" },
    "cpr": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO, label: "CUBASE" },
    "ptx": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO, label: "PRO_TL" },
    "logic": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO, label: "LOGIC" },
    "sf2": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO, label: "S_FONT" },
    "vst": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO, label: "VST" },
    "vst3": { ...ICON_THEMES.AUDIO, icon: ICON_PATHS.AUDIO, label: "VST3" },

    // IMAGES / DESIGN / VFX
    "jpg": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE },
    "jpeg": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE },
    "png": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE },
    "gif": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE },
    "svg": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE },
    "webp": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE },
    "psd": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE, label: "PHOTO" },
    "ai": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE, label: "ILLUST" },
    "ico": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE },
    "bmp": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE },
    "tiff": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE },
    "heic": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE },
    "raw": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE },
    "eps": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE, label: "VECTOR" },
    "cr2": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE, label: "CANON" },
    "nef": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE, label: "NIKON" },
    "dng": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE, label: "RAW" },
    "xcf": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE, label: "GIMP" },
    "tga": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE, label: "TARGA" },
    "dds": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE, label: "TEX" },
    "exr": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE, label: "HDR" },
    "indd": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE, label: "INDESN" },
    "cdr": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE, label: "CORElL" },
    "sketch": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE, label: "SKETCH" },
    "fig": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE, label: "FIGMA" },
    "pbm": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE },
    "pgm": { ...ICON_THEMES.IMAGE, icon: ICON_PATHS.IMAGE },

    // EXECUTABLES
    "exe": { ...ICON_THEMES.APP, icon: ICON_PATHS.APP },
    "msi": { ...ICON_THEMES.APP, icon: ICON_PATHS.APP, label: "INSTALL" },
    "app": { ...ICON_THEMES.APP, icon: ICON_PATHS.APP },

    "deb": { ...ICON_THEMES.APP, icon: ICON_PATHS.APP, label: "LINUX" },
    "rpm": { ...ICON_THEMES.APP, icon: ICON_PATHS.APP, label: "LINUX" },
    "bat": { ...ICON_THEMES.APP, icon: ICON_PATHS.APP, label: "BATCH" },
    "sh": { ...ICON_THEMES.APP, icon: ICON_PATHS.APP, label: "SHELL" },
    "cmd": { ...ICON_THEMES.APP, icon: ICON_PATHS.APP, label: "CMD" },

    // CODE / DEVELOPER TOOLS
    "html": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE },
    "css": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE },
    "js": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE },
    "py": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "PYTHON" },
    "java": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE },
    "cpp": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "C++" },
    "c": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE },
    "cs": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "C#" },
    "lua": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE },
    "tsx": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "REACT" },
    "jsx": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "REACT" },
    "go": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "GOLANG" },
    "rb": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "RUBY" },
    "rs": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "RUST" },
    "php": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "PHP" },
    "kt": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "KOTLIN" },
    "swift": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "SWIFT" },
    "dart": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "DART" },
    "sass": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "SASS" },
    "scss": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "SCSS" },
    "dockerfile": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "DOCKER" },
    "tf": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "TERRAF" },
    "pl": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "PERL" },
    "r": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "R_LANG" },
    "groovy": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE },
    "scala": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "SCALA" },
    "asm": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "ASM" },
    "wasm": { ...ICON_THEMES.CODE, icon: ICON_PATHS.CODE, label: "WASM" },

    // DATA / GIS / ACADEMIC
    "json": { ...ICON_THEMES.DATA, icon: ICON_PATHS.DATA },
    "xml": { ...ICON_THEMES.DATA, icon: ICON_PATHS.DATA },
    "yaml": { ...ICON_THEMES.DATA, icon: ICON_PATHS.DATA },
    "sql": { ...ICON_THEMES.DATA, icon: ICON_PATHS.DATA },
    "sqlite": { ...ICON_THEMES.DATA, icon: ICON_PATHS.DATA, label: "SQLITE" },
    "csv": { ...ICON_THEMES.DATA, icon: ICON_PATHS.DOC },
    "tsv": { ...ICON_THEMES.DATA, icon: ICON_PATHS.DATA, label: "TAB" },
    "hdf5": { ...ICON_THEMES.DATA, icon: ICON_PATHS.DATA, label: "HDF5" },
    "avro": { ...ICON_THEMES.DATA, icon: ICON_PATHS.DATA, label: "AVRO" },
    "parquet": { ...ICON_THEMES.DATA, icon: ICON_PATHS.DATA, label: "PARQ" },
    "shp": { ...ICON_THEMES.DATA, icon: ICON_PATHS.DATA, label: "GIS" },
    "kml": { ...ICON_THEMES.DATA, icon: ICON_PATHS.DATA, label: "KML" },
    "geojson": { ...ICON_THEMES.DATA, icon: ICON_PATHS.DATA, label: "GEOJSN" },
    "ndjson": { ...ICON_THEMES.DATA, icon: ICON_PATHS.DATA, label: "NDJSON" },
    "db": { ...ICON_THEMES.DATA, icon: ICON_PATHS.DATA, label: "DB" },

    // FONTS
    "ttf": { ...ICON_THEMES.FONT, icon: ICON_PATHS.FONT },
    "otf": { ...ICON_THEMES.FONT, icon: ICON_PATHS.FONT },
    "woff": { ...ICON_THEMES.FONT, icon: ICON_PATHS.FONT },
    "woff2": { ...ICON_THEMES.FONT, icon: ICON_PATHS.FONT },

    // CONFIG / LOGS / DESKTOP
    "bak": { ...ICON_THEMES.CONFIG, icon: ICON_PATHS.CONFIG, label: "BACKUP" },
    "tmp": { ...ICON_THEMES.CONFIG, icon: ICON_PATHS.CONFIG, label: "TEMP" },
    "log": { ...ICON_THEMES.CONFIG, icon: ICON_PATHS.CONFIG },
    "ini": { ...ICON_THEMES.CONFIG, icon: ICON_PATHS.CONFIG },
    "cfg": { ...ICON_THEMES.CONFIG, icon: ICON_PATHS.CONFIG },
    "conf": { ...ICON_THEMES.CONFIG, icon: ICON_PATHS.CONFIG },
    "env": { ...ICON_THEMES.CONFIG, icon: ICON_PATHS.CONFIG, label: "ENV" },
    "toml": { ...ICON_THEMES.CONFIG, icon: ICON_PATHS.CONFIG, label: "TOML" },
    "lock": { ...ICON_THEMES.CONFIG, icon: ICON_PATHS.CONFIG, label: "LOCK" },
    "lnk": { ...ICON_THEMES.CONFIG, icon: ICON_PATHS.CONFIG, label: "SHORT" },
    "desktop": { ...ICON_THEMES.CONFIG, icon: ICON_PATHS.CONFIG, label: "LINUX" },
    "plist": { ...ICON_THEMES.CONFIG, icon: ICON_PATHS.CONFIG, label: "APPLE" },
    "prefs": { ...ICON_THEMES.CONFIG, icon: ICON_PATHS.CONFIG, label: "PREFS" },

    // 3D MODELING / CAD / ARCHITECTURE / PRINTING
    "3mf": { ...ICON_THEMES.PRINT3D, icon: ICON_PATHS.PRINT3D },
    "stl": { ...ICON_THEMES.PRINT3D, icon: ICON_PATHS.PRINT3D },
    "step": { ...ICON_THEMES.PRINT3D, icon: ICON_PATHS.PRINT3D },
    "gcode": { ...ICON_THEMES.PRINT3D, icon: ICON_PATHS.PRINT3D, label: "GCODE" },
    "obj": { ...ICON_THEMES.PRINT3D, icon: ICON_PATHS.PRINT3D, label: "OBJ" },
    "fbx": { ...ICON_THEMES.PRINT3D, icon: ICON_PATHS.PRINT3D, label: "FBX" },
    "blend": { ...ICON_THEMES.PRINT3D, icon: ICON_PATHS.PRINT3D, label: "BLEND" },
    "dae": { ...ICON_THEMES.PRINT3D, icon: ICON_PATHS.PRINT3D, label: "COLLAD" },
    "dwg": { ...ICON_THEMES.PRINT3D, icon: ICON_PATHS.PRINT3D, label: "AUTOCD" },
    "dxf": { ...ICON_THEMES.PRINT3D, icon: ICON_PATHS.PRINT3D },
    "skp": { ...ICON_THEMES.PRINT3D, icon: ICON_PATHS.PRINT3D, label: "SKETCH" },
    "rvt": { ...ICON_THEMES.PRINT3D, icon: ICON_PATHS.PRINT3D, label: "REVIT" },
    "ifc": { ...ICON_THEMES.PRINT3D, icon: ICON_PATHS.PRINT3D, label: "BIM" },
    "ply": { ...ICON_THEMES.PRINT3D, icon: ICON_PATHS.PRINT3D },
    "iges": { ...ICON_THEMES.PRINT3D, icon: ICON_PATHS.PRINT3D, label: "IGES" },
    "igs": { ...ICON_THEMES.PRINT3D, icon: ICON_PATHS.PRINT3D },

    // OTHERS
    "torrent": { ...ICON_THEMES.ARCHIVE, icon: ICON_PATHS.ARCHIVE, label: "TORRNT" },
    "nfo": { ...ICON_THEMES.DOC, icon: ICON_PATHS.DOC, label: "INFO" },
    "crypto": { ...ICON_THEMES.CODE, icon: ICON_PATHS.SYSTEM, label: "SECURE" }
};
